# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uploader.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 207)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        Form.setFont(font)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.groupBox_2.setFont(font)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label_save_key = QtWidgets.QLabel(self.groupBox_2)
        self.label_save_key.setObjectName("label_save_key")
        self.gridLayout.addWidget(self.label_save_key, 0, 0, 1, 1)
        self.pushButton_explore_save_key = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_explore_save_key.setObjectName("pushButton_explore_save_key")
        self.gridLayout.addWidget(self.pushButton_explore_save_key, 0, 3, 1, 1)
        self.pushButton_save_key = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_save_key.setObjectName("pushButton_save_key")
        self.gridLayout.addWidget(self.pushButton_save_key, 1, 3, 1, 1)
        self.label_save_flag = QtWidgets.QLabel(self.groupBox_2)
        self.label_save_flag.setText("")
        self.label_save_flag.setObjectName("label_save_flag")
        self.gridLayout.addWidget(self.label_save_flag, 1, 0, 1, 2)
        self.lineEdit_save_key = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_save_key.setObjectName("lineEdit_save_key")
        self.gridLayout.addWidget(self.lineEdit_save_key, 0, 2, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_explore_load_pic = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_explore_load_pic.setObjectName("pushButton_explore_load_pic")
        self.gridLayout_2.addWidget(self.pushButton_explore_load_pic, 1, 2, 1, 1)
        self.lineEdit_load_key = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_load_key.setObjectName("lineEdit_load_key")
        self.gridLayout_2.addWidget(self.lineEdit_load_key, 0, 1, 1, 1)
        self.label_load_key = QtWidgets.QLabel(self.groupBox)
        self.label_load_key.setObjectName("label_load_key")
        self.gridLayout_2.addWidget(self.label_load_key, 0, 0, 1, 1)
        self.label_load_pic = QtWidgets.QLabel(self.groupBox)
        self.label_load_pic.setObjectName("label_load_pic")
        self.gridLayout_2.addWidget(self.label_load_pic, 1, 0, 1, 1)
        self.lineEdit_load_pic = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_load_pic.setObjectName("lineEdit_load_pic")
        self.gridLayout_2.addWidget(self.lineEdit_load_pic, 1, 1, 1, 1)
        self.pushButton_explore_load_key = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_explore_load_key.setObjectName("pushButton_explore_load_key")
        self.gridLayout_2.addWidget(self.pushButton_explore_load_key, 0, 2, 1, 1)
        self.label_encryt_flag = QtWidgets.QLabel(self.groupBox)
        self.label_encryt_flag.setText("")
        self.label_encryt_flag.setObjectName("label_encryt_flag")
        self.gridLayout_2.addWidget(self.label_encryt_flag, 2, 0, 1, 1)
        self.pushButton_save_encrypt_pic = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_save_encrypt_pic.setObjectName("pushButton_save_encrypt_pic")
        self.gridLayout_2.addWidget(self.pushButton_save_encrypt_pic, 2, 2, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_save_key.setText(_translate("Form", "保存临时随机密钥"))
        self.pushButton_explore_save_key.setText(_translate("Form", "浏览"))
        self.pushButton_save_key.setText(_translate("Form", "保存"))
        self.pushButton_explore_load_pic.setText(_translate("Form", "浏览"))
        self.label_load_key.setText(_translate("Form", "加载密钥文件"))
        self.label_load_pic.setText(_translate("Form", "选择加密图片"))
        self.pushButton_explore_load_key.setText(_translate("Form", "浏览"))
        self.pushButton_save_encrypt_pic.setText(_translate("Form", "加密并保存"))
